force-app/main/default/objects/Account/fields/StockClosePrice__c.field-meta.xml
<CustomField>
    <fullName>StockClosePrice__c</fullName>
    <label>Stock Close Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/StockLastRefreshedDate__c.field-meta.xml
<CustomField>
    <fullName>StockLastRefreshedDate__c</fullName>
    <label>Stock Last Refreshed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHandler.cls
public with sharing class AccountTriggerHandler {

    // -------------------------------------------------------
    // INSERT
    // -------------------------------------------------------

    public void handleBeforeInsert( List<Account> newList ) {

        // no logic yet

    }

    public void handleAfterInsert( List<Account> newList, Map<ID, Account> newMap ) {

        // no logic yet

    }

    // -------------------------------------------------------
    // UPDATE
    // -------------------------------------------------------

    public void handleBeforeUpdate( List<Account> oldList, Map<ID, Account> oldMap,
                                    List<Account> newList, Map<ID, Account> newMap ) {

        for ( Account newAccount : newList ) {

            Account oldAccount = oldMap.get( newAccount.Id );

            Boolean tickerSymbolChanged = ( oldAccount.TickerSymbol != newAccount.TickerSymbol );

            if ( tickerSymbolChanged ) {
                clearStockFields( newAccount );
            }

        }

    }

    public void handleAfterUpdate( List<Account> oldList, Map<ID, Account> oldMap,
                                   List<Account> newList, Map<ID, Account> newMap ) {

        // no logic yet

    }

    // -------------------------------------------------------
    // DELETE
    // -------------------------------------------------------

    public void handleBeforeDelete( List<Account> oldList, Map<ID, Account> oldMap ) {

        // no logic yet

    }

    public void handleAfterDelete( List<Account> oldList, Map<ID, Account> oldMap ) {

        // no logic yet

    }

    // -------------------------------------------------------

    public static void clearStockFields( Account acct ) {
        acct.StockClosePrice__c = null;
        acct.StockLastRefreshedDate__c = null;
    }

}